### ISSUE TITLE
Equation solving

### ISSUE THREAD

**Issue by matveysiva** [HPI-SWA-Teaching/SWT16-Project-06#244]
As a user, I want to directly see the result of an equation I entered in order to minimize my interactions with Algernon.

**Comment by LinqLover** [comment]
Just curious: Why restrict this feature to mathematical expressions only? I would find it very exciting if we could see the preview of any other Smalltalk expression (`Float pi i exp`, `'foo' capitalized`, ...) as well. :-)

**Comment by LinqLover** [comment]
Probably related: https://github.com/hpi-swa-teaching/Algernon-Launcher/issues/173

**Comment by EliasNotFound** [comment]
@LinqLover 

> Just curious: Why restrict this feature to mathematical expressions only? I would find it very exciting if we could see the preview of any other Smalltalk expression (`Float pi i exp`, `'foo' capitalized`, ...) as well. :-)

The initial idea came by looking at Spotlight which directly gives you the solution for an equation. We did not implement anything else yet because Algernon would have to execute the command after every key input and would therefore need to catch a lot of errors. But we might think about adding this functionality in a future issue.

**Comment by LinqLover** [comment]
Thanks for the explanation! Error handling should be pretty straightforward using a generic exception handler (`[self doSomething] on: Error do: [:ex | ex messageText]`) and you could eliminate all unexpected side effects by using `Sandbox`. I'm looking forward to your future plans! :D
